# Generated by Django 4.2.1 on 2024-10-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_evaluations_evaluations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='evaluations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluat', to='Users.evaluations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_hom', to='Users.home_work'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedul', to='Users.schedule'),
        ),
    ]
