# Generated by Django 4.2.1 on 2024-10-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_evaluations_alter_user_home_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='predment',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
