# Generated by Django 4.2.1 on 2024-10-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_predment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
