# Generated by Django 4.2.1 on 2024-10-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_user_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regalia_teacher',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
