# Generated by Django 4.2.1 on 2024-12-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_user_regalia_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='schedule',
        ),
        migrations.AddField(
            model_name='user',
            name='schedule',
            field=models.ManyToManyField(related_name='students', to='Users.schedule'),
        ),
    ]
