# Generated by Django 4.2.1 on 2024-12-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_remove_schedule_schedule_schedule_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_t',
            field=models.CharField(default=None, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule', to='Users.schedule'),
        ),
    ]
