# Generated by Django 4.2.1 on 2024-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_user_id_t_alter_user_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='predment',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
