# Generated by Django 4.2.1 on 2025-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_schedule_predment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
