# Generated by Django 4.2.1 on 2025-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_teacher',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
