# Generated by Django 4.2.1 on 2025-02-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_schedule_id_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='predment',
            new_name='id_student',
        ),
    ]
