# Generated by Django 4.2.1 on 2025-02-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_rename_predment_schedule_id_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='photo/'),
        ),
    ]
