# Generated by Django 4.2.1 on 2025-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_rename_predment_schedule_id_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_teacher',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
