# Generated by Django 4.2.1 on 2025-03-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
